
GET {{url}}/employee
Content-Type: application/json

###

GET {{url}}/employee/1
Content-Type: application/json

###

POST {{url}}/employee
Content-Type: application/json

{
  "firstName": "Ziko",
  "lastName": "Jaki",
  "title": "Employees",
  "email": "din@hot.dk",
  "phone": 54788545,
  "managerId": 1
}


###

PUT {{url}}/employee/1
Content-Type: application/json

{
  "employeeId": 1,
  "firstName": "Marco",
  "lastName": "Polloyee",
  "title": "Developer",
  "email": "dinlille@hot.dk",
  "phone": 54658545
}

